// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1mNueVsy6EW7IQwlffNw-qtfNGRg5fI8',
    appId: '1:109031174232:web:122f4bec0341f027705a2d',
    messagingSenderId: '109031174232',
    projectId: 'salahkassab-dc9a2',
    authDomain: 'salahkassab-dc9a2.firebaseapp.com',
    storageBucket: 'salahkassab-dc9a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuELWbBoHTOjeRiiM88Bt3DlRwk81tRbU',
    appId: '1:109031174232:android:4207dbb9b2b202f8705a2d',
    messagingSenderId: '109031174232',
    projectId: 'salahkassab-dc9a2',
    storageBucket: 'salahkassab-dc9a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhGe0o28F42S3JUFc-1ksvG3jA2V4ZjeI',
    appId: '1:109031174232:ios:0ffc7a99e881b1f7705a2d',
    messagingSenderId: '109031174232',
    projectId: 'salahkassab-dc9a2',
    storageBucket: 'salahkassab-dc9a2.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhGe0o28F42S3JUFc-1ksvG3jA2V4ZjeI',
    appId: '1:109031174232:ios:cd7361d53178a720705a2d',
    messagingSenderId: '109031174232',
    projectId: 'salahkassab-dc9a2',
    storageBucket: 'salahkassab-dc9a2.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
